"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys
from dotenv import load_dotenv # 1. Import thư viện
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

env_path = BASE_DIR.parent / '.env'

load_dotenv(dotenv_path=env_path) # 2. Load file .env

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
     
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'user', 
    'lesson',
    'channels'
]

ASGI_APPLICATION = 'core.asgi.application'
# Cấu trúc: 'tên_app.Tên_Class_Model'
AUTH_USER_MODEL = 'user.User'

AUTHENTICATION_BACKENDS = [
    'user.backends.MultiFieldModelBackend', # Đường dẫn tới file bạn vừa tạo
    'django.contrib.auth.backends.ModelBackend',
]

CELERY_BEAT_SCHEDULE = {
    'delete-inactive-users-every-midnight': {
        'task': 'user.tasks.cleanup_inactive_users', # Sửa tên function cho đúng với tasks.py
        'schedule': crontab(hour=0, minute=0), # Chạy lúc 00:00 mỗi đêm
    },

    # Task xóa Session hết hạn (THÊM MỚI)
    'cleanup-expired-sessions-daily': {
        'task': 'user.tasks.cleanup_expired_sessions', # Bỏ chữ apps.
        'schedule': crontab(hour=0, minute=30), # Chạy lúc 00:30 đêm (sau task xóa user 30p)
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', # Thêm dòng này
    ),
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py

# Cấu hình gửi Mail (Dùng App Password của Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://redis:6379/1", # Tên service redis trong docker-compose
        "LOCATION": "redis://127.0.0.1:6379/1", # Dùng localhost khi chạy local
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USERNAME'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'



# 1. Khai báo Backend (Dành cho Django 4.2+ nên dùng STORAGES)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 2. Thông số từ Supabase (Đảm bảo các biến env này KHÔNG có https:// ở đầu nếu Linh tự nối)
AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_S3_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_S3_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = 'avatars'

# ENDPOINT chuẩn của Supabase có dạng: https://[project-id].supabase.co/storage/v1/s3
AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_S3_ENDPOINT')

# 3. Cấu hình URL để hiển thị ảnh
# Với Supabase, URL công khai sẽ có dạng: https://[id].supabase.co/storage/v1/object/public/avatars/
AWS_S3_CUSTOM_DOMAIN = f"{os.getenv('SUPABASE_PROJECT_ID')}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# 4. Các cấu hình bổ sung
AWS_S3_FILE_OVERWRITE = False
AWS_S3_QUERYSTRING_AUTH = False 
AWS_DEFAULT_ACL = None

# ===== CORS Configuration (cho Frontend React) =====
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',    # Vite dev server
    'http://127.0.0.1:5173',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Cho phép FE gửi cookies/credentials (nếu cần)
CORS_ALLOW_CREDENTIALS = True
