services:
  db:
    build: . # Sẽ tự build từ Dockerfile ở Bước 2
    container_name: turtle_container
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Volume này giúp dữ liệu được lưu lại sau khi tắt container
      - postgres_data:/var/lib/postgresql/data
    restart: no

volumes:
  postgres_data:
