# Generated by Django 6.0.3 on 2026-05-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(help_text='Số thứ tự chặng (1 đến 10)')),
                ('is_completed', models.BooleanField(default=False)),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stage_progress',
                'ordering': ['stage_number'],
                'unique_together': {('user', 'stage_number')},
            },
        ),
    ]
