services:
  redis:
    image: redis:7-alpine
    container_name: turtle_redis_container
    ports:
      - "6379:6379"

  web:
    build:
      # Context đặt ở '.' (thư mục Back-end/) để Dockerfile thấy pyproject.toml
      context: .
      dockerfile: docker/docker_env/dockerfile
    container_name: turtle_web_container
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  # CELERY WORKER: Thằng này đi gửi OTP, gửi Mail (Làm việc ngay)
  celery_worker:
    build: .
    container_name: turtle_worker
    command: celery -A core_root worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  # CELERY BEAT: Thằng này canh đồng hồ để xóa User 30 ngày (Lên lịch)
  celery_beat:
    build: .
    container_name: turtle_beat
    command: celery -A core_root beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

