# Generated by Django 6.0.3 on 2026-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_usersession_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_commands',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
