# Generated by Django 6.0.3 on 2026-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_custom_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_title',
            field=models.CharField(default='Hiệp sĩ tập sự', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='unlocked_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
