# Generated by Django 6.0.3 on 2026-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_selected_title_user_unlocked_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_title',
            field=models.CharField(default='Hiệp Sĩ Tập Sự ⚔️', max_length=50),
        ),
    ]
